name: Test

on:
  push:
    branches: [ "main" ]
    paths: rust-server
  pull_request:
    branches: [ "main" ]
    paths: rust-server

env:
  CARGO_TERM_COLOR: always

jobs:
  backend_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rust-server
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

## TODO add frontend tests 