name: backend_test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  backend_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rust-server
    steps:
    - uses: actions/checkout@v3
    - name: Filter files
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          backend:
            - 'rust-server/**'
    - name: Build
      if: steps.filter.outputs.backend == 'true'
      run: cargo build --verbose
    - name: Run tests
      if: steps.filter.outputs.backend == 'true'
      run: cargo test --verbose